animations = true;
animation-stiffness = 300.0;
animation-dampening = 35.0;
animation-clamping = true;
animation-mass = 1;
animation-for-open-window = "zoom";
animation-for-menu-window = "slide-down";
animation-for-transient-window = "slide-down";

corner-radius = 30;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.4;

active-opacity = 1.0;
inactive-opacity = 0.85;
frame-opacity = 1.0;

blur: {
  method = "dual_kawase";
  strength = 5;
  background = true;
  background-frame = false;
  background-fixed = false;
}

opacity-rule = [
  "100:class_g = 'Chromium'",
  "100:class_g = 'Evince'",
  "90:class_g = 'Alacritty'",
  "95:class_g = 'Thunar'"
];

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

backend = "glx";
vsync = true;
use-damage = true;
glx-no-stencil = true;
glx-copy-from-front = false;
unredir-if-possible = true;

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 10;

